name: Build and deploy package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@main

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    
    - name: Build with dotnet
      run: actions/setup-dotnet@v1

    - name: Test
      run: dotnet test

    - name: Create the Package
      run: dotnet pack --configuration Release


dotnet nuget push "./Gravatar.bin.Release/Gravatar.1.0.0.nupkg" -k ${{ secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json